// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: P_ClientServer.proto

package protocol;

public final class ClientServerProtocol {
  private ClientServerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2SLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .PBLogin login = 1;
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    boolean hasLogin();
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    protocol.BaseType.PBLogin getLogin();
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    protocol.BaseType.PBLoginOrBuilder getLoginOrBuilder();
  }
  /**
   * Protobuf type {@code C2SLogin}
   */
  public static final class C2SLogin extends
      com.google.protobuf.GeneratedMessage
      implements C2SLoginOrBuilder {
    // Use C2SLogin.newBuilder() to construct.
    private C2SLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SLogin defaultInstance;
    public static C2SLogin getDefaultInstance() {
      return defaultInstance;
    }

    public C2SLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.BaseType.PBLogin.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(protocol.BaseType.PBLogin.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ClientServerProtocol.internal_static_C2SLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ClientServerProtocol.internal_static_C2SLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ClientServerProtocol.C2SLogin.class, protocol.ClientServerProtocol.C2SLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SLogin> PARSER =
        new com.google.protobuf.AbstractParser<C2SLogin>() {
      public C2SLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .PBLogin login = 1;
    public static final int LOGIN_FIELD_NUMBER = 1;
    private protocol.BaseType.PBLogin login_;
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    public protocol.BaseType.PBLogin getLogin() {
      return login_;
    }
    /**
     * <code>required .PBLogin login = 1;</code>
     */
    public protocol.BaseType.PBLoginOrBuilder getLoginOrBuilder() {
      return login_;
    }

    private void initFields() {
      login_ = protocol.BaseType.PBLogin.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLogin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLogin().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, login_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, login_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.ClientServerProtocol.C2SLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.ClientServerProtocol.C2SLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2SLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.ClientServerProtocol.C2SLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ClientServerProtocol.internal_static_C2SLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ClientServerProtocol.internal_static_C2SLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ClientServerProtocol.C2SLogin.class, protocol.ClientServerProtocol.C2SLogin.Builder.class);
      }

      // Construct using protocol.ClientServerProtocol.C2SLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (loginBuilder_ == null) {
          login_ = protocol.BaseType.PBLogin.getDefaultInstance();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ClientServerProtocol.internal_static_C2SLogin_descriptor;
      }

      public protocol.ClientServerProtocol.C2SLogin getDefaultInstanceForType() {
        return protocol.ClientServerProtocol.C2SLogin.getDefaultInstance();
      }

      public protocol.ClientServerProtocol.C2SLogin build() {
        protocol.ClientServerProtocol.C2SLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ClientServerProtocol.C2SLogin buildPartial() {
        protocol.ClientServerProtocol.C2SLogin result = new protocol.ClientServerProtocol.C2SLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ClientServerProtocol.C2SLogin) {
          return mergeFrom((protocol.ClientServerProtocol.C2SLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ClientServerProtocol.C2SLogin other) {
        if (other == protocol.ClientServerProtocol.C2SLogin.getDefaultInstance()) return this;
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLogin()) {
          
          return false;
        }
        if (!getLogin().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ClientServerProtocol.C2SLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ClientServerProtocol.C2SLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .PBLogin login = 1;
      private protocol.BaseType.PBLogin login_ = protocol.BaseType.PBLogin.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.BaseType.PBLogin, protocol.BaseType.PBLogin.Builder, protocol.BaseType.PBLoginOrBuilder> loginBuilder_;
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public protocol.BaseType.PBLogin getLogin() {
        if (loginBuilder_ == null) {
          return login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public Builder setLogin(protocol.BaseType.PBLogin value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public Builder setLogin(
          protocol.BaseType.PBLogin.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public Builder mergeLogin(protocol.BaseType.PBLogin value) {
        if (loginBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              login_ != protocol.BaseType.PBLogin.getDefaultInstance()) {
            login_ =
              protocol.BaseType.PBLogin.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = protocol.BaseType.PBLogin.getDefaultInstance();
          onChanged();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public protocol.BaseType.PBLogin.Builder getLoginBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      public protocol.BaseType.PBLoginOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_;
        }
      }
      /**
       * <code>required .PBLogin login = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.BaseType.PBLogin, protocol.BaseType.PBLogin.Builder, protocol.BaseType.PBLoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.BaseType.PBLogin, protocol.BaseType.PBLogin.Builder, protocol.BaseType.PBLoginOrBuilder>(
                  login_,
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:C2SLogin)
    }

    static {
      defaultInstance = new C2SLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C2SLogin)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C2SLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2SLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024P_ClientServer.proto\032\020P_BaseType.proto" +
      "\"#\n\010C2SLogin\022\027\n\005login\030\001 \002(\0132\010.PBLoginB \n" +
      "\010protocolB\024ClientServerProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_C2SLogin_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_C2SLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C2SLogin_descriptor,
              new java.lang.String[] { "Login", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.BaseType.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
